### PR TITLE
homework.streams.part2.exercise1 (Mikhaylov)

### PR DESCRIPTION
**Pull request by vm137**

### CODE REVIEW

**Comment by AnyaYu** [comment]
Please, create a pull request to the branch with your last name

**Comment by vm137** [comment]
renamed.

**Comment by AnyaYu** [comment]
The branch you want to merge to is still incorrect: elefus:homework.streams.part2.exercise1

**Comment by vm137** [comment]
yes. sorry. 
fixed.

**Review by AnyaYu — APPROVED** [review]

**Review by AnyaYu — APPROVED** [review]

**Review by AlexMem — APPROVED** [review]

**Pull request merged**
